loginreg/booking/urls.py
from django.urls import path, include
from . import views

app_name = 'booking'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:subject_id>/booking', views.bookings, name='booking'),

]

loginreg/enrollment/urls.py
from django.urls import path
from . import views

urlpatterns = [
]

loginreg/loginreg/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('booking/', include('booking.urls')),
    path('enrollment/', include('enrollment.urls')),
    path('users/', include('users.urls')),
]

loginreg/users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),

]

loginreg/booking/models.py
from django.db import models
from django.contrib.auth.models import User

# from loginreg import booking

# Create your models here.
class Subject(models.Model):
    class_number = models.CharField(max_length=5, default="")
    subject_name = models.CharField(max_length=64, default="")
    section = models.CharField(max_length=10, default="")
    semester = models.CharField(max_length=10, default="")
    year = models.CharField(max_length=10, default="")
    seatss = models.CharField(max_length=10, default="")

    def __str__(self):
        return f"{self.class_number} {self.subject_name} {self.section} {self.semester} {self.year} {self.seatss}"

class Booking(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default="")
    course_number = models.ForeignKey(Subject, on_delete=models.CASCADE, default="")
    
    def __str__(self):
        return f"{self.user} {self.course_number}"

##class ShowBooking(models.Model):
    ##show_me = models.CharField

#class Student(models.Model):
    ##first = models.CharField(max_length=64)
    ##last = models.CharField(max_length=64)
    ##booking = models.ManyToManyField(Booking, blank=True, related_name="student")

    ##def __str__(self):
        ##return f"{ self.first } { self.last }"

loginreg/enrollment/models.py
from django.db import models

# Create your models here.

loginreg/users/models.py
from django.db import models

# Create your models here.

loginreg/booking/views.py
from ast import Sub
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from django.urls import reverse
from django.contrib.auth.models import User
from .models import Booking


from .models import Booking, Subject
# Create your views here.

def index(request):
    # who
    user = User.objects.get(pk=request.user.id)

    # enrolled subject
    enrolled_subjects = Booking.objects.filter(user=user)

    id = []
    for subject in enrolled_subjects:
        id.append(subject.course_number.id)
    subjects = Subject.objects.exclude(pk__in=id)

    return render(request, "booking/index.html",{
        'subjects': subjects
    })

def bookings(request, subject_id):
    user = User.objects.get(pk=request.user.id)
    subject = Subject.objects.get(id=subject_id)

    check = Booking.objects.filter(user=user, course_number=subject).first()

    if check is None:
        booking = Booking.objects.create(user=user, course_number=subject)

        subjects = Booking.objects.filter(user=user)
        print(subject)
        return render(request,'booking/booking.html', {
            'subjects': subjects,
        })

    # try:
    #     user = User.objects.get(pk=request.user.id)
    #     subject = Subject.objects.get(id=subject_id)

    #     check = Booking.objects.get(user=user, course_number=subject)
    #     print('check:', check)
    #     if not check:
    #         booking = Booking.objects.create(user=user, course_number=subject)
    #     ##showbooking = Booking.objects.filter(user=user) 

    #         subject = Booking.objects.filter(user=user)
    #         print(subject)
    #         return render(request,'booking/booking.html', {
    #             'bookings': bookings,
    #         })
    # except Exception as e:
    #     print("Error on booking : ", e)
    # return index(request)

   
        

# def showbooking(request):
#     try:
#         user = User.objects.get(pk=request.user.id)
#         showbooking = Booking.objects.values_list('course_number')
#         return render(request, 'booking/showbooking.html', {
#             'showbookings' : showbooking,
#         })
#     except Exception as e:
#         print("Error on showing : ", e)
#     return index(request)

    
    


#def index(request):
#   return render(request, "subject/index.html",{
#       'subject': Subject.objects.all()
#   })

loginreg/enrollment/views.py
from django.shortcuts import render

# Create your views here.

loginreg/users/views.py
from urllib import request
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.urls import reverse

# Create your views here.

def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('login'))
    return render(request, 'users/index.html')

def login_view(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('index'))
        else:
            return render(request, 'users/login.html', {
                'message': 'Invalid credentials.'
            })
    return render(request, 'users/login.html')

def logout_view(request):
    logout(request)
    return render(request, 'users/login.html', {
        'message': 'You are logged out.'
    })

loginreg/booking/templates/booking/booking.html
{% extends 'booking/layout.html' %}
{% block body %}
<h2>Registered Courses</h2>
<ul>
    {% for subject in subjects %}
    <li> {{ subject }} </li>
    <!--
    <li> {{ users.last_name}} </li>
    <li> {{ users.username}} </li>
    <li> {{ users.subject}} </li>-->
    {% empty %}
    <li> No user. </li>
    {% endfor %}
</ul>


<a href="{% url 'booking:index' %}">Back to Booking List</a>
{% endblock %}

loginreg/booking/templates/booking/index.html
{% extends 'booking/layout.html' %}
{% block body %}

<h1>Subject List</h1>
{% if subjects %}
<table>
    <tr>
      <th>Code</th>
      <th>Name</th>
      <th>Section</th>
      <th>Semester</th>
      <th>Year</th>
      <th>Available Seat</th>
      <th>button</th>      
    </tr>
    {% for subject in subjects %}
    <tr>
        <td>{{ subject.class_number }}</td>
        <td>{{ subject.subject_name }}</td>
        <td>{{ subject.section }}</td>
        <td>{{ subject.semester }}</td>
        <td>{{ subject.year }}</td>
        <td>{{ subject.seats }}</td>
        <td>
            <form action="{% url 'booking:booking' subject.id %}" method="post" >
                {% csrf_token %}
                <button type="submit">enroll</button>
            </form>
        </td>
    </tr>
    {% endfor %}
</table>
{% endif %}
<ul>
    {% for subject in subjects %}
    <li>{{ subject.class_number }}</li>
    <li>{{ subject.subject_name }}</li>
    <form action="{% url 'booking:booking' subject.id %}" method="post" >
        {% csrf_token %}
        <button type="submit">enroll</button>
    </form>
    <br></br>
    {% empty %}
    <li> No booking. </li>
    {% endfor %}

</ul>


{% endblock %}

loginreg/booking/templates/booking/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Booking</title>
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>

</html>

loginreg/users/templates/users/index.html
{% extends 'users/layout.html' %}
{% block body %}
<h1>Welcome, {{ request.user.first_name }}</h1>
<ul>
    <li>Username: {{ request.user.username }}</li>
    <li>Email: {{ request.user.email }}</li>
</ul>

<a href="{% url 'logout' %}">Log out</a>
<a href="/booking">Subject list</a>

{% endblock %}

loginreg/users/templates/users/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Booking</title>
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>

</html>

loginreg/users/templates/users/login.html
{% extends 'users/layout.html' %}
{% block body %}

<h1>login</h1>

{% if message %}
    <div style="color:red">{{ message }}</div>
{% endif %}

<form action="{% url 'login' %}" method="post">
    {% csrf_token %}
    <input type="text" name="username" placeholder="Username">
    <input type="password" name="password" placeholder="Password">
    <input type="submit" value="Login"> 

</form>



{% endblock %}